version: "3.9"
services:
  webapi_1:
    build: webapi/.
    environment:
      RABBITMQ_URL: amqp://user:passwd@rabbit:5672/%2F
      NAME: webapi_1

  webapi_2:
    build: webapi/.
    environment:
      RABBITMQ_URL: amqp://user:passwd@rabbit:5672/%2F
      NAME: webapi_2

  solver:
    build: solver/.
    restart: on-failure
    depends_on:
      - rabbit
      - nginx
      - redis
    links:
      - rabbit
      - nginx
      - redis
    environment:
      RABBITMQ_URL: amqp://user:passwd@rabbit:5672/%2F
      CACHE_HOST: redis

  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: passwd
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 10

  nginx:
    build: nginx/.
    ports:
      - "8080:80"
    depends_on:
      - webapi_1
      - webapi_2
    links:
      - webapi_1
      - webapi_2

  redis:
    image: redis
